version: '3'
services:
  nginx:
    container_name: nginx-rate
    image: nginx
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./:/www
    ports:
      - 8088:80
    restart: on-failure
    depends_on:
      - php

  php:
    container_name: php-rate
    build: .
    restart: on-failure
    volumes:
      - ./:/www
